"""
Configuration file for traffic simulation
Contains all adjustable parameters for easy tweaking
"""

# Screen settings
SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
FPS = 60

# Colors
COLOR_ROAD = (50, 50, 50)
COLOR_GRASS = (34, 139, 34)
COLOR_LANE_MARKING = (255, 255, 255)
COLOR_CROSSWALK = (240, 240, 240)
COLOR_CAR_NORMAL = (70, 130, 255)
COLOR_CAR_TRUCK = (200, 100, 50)
COLOR_CAR_SPORTS = (255, 50, 50)
COLOR_AMBULANCE = (255, 255, 0)
COLOR_AMBULANCE_STRIPE = (255, 0, 0)
COLOR_PEDESTRIAN = (150, 75, 0)
COLOR_TEXT = (255, 255, 255)
COLOR_LIGHT_RED = (255, 0, 0)
COLOR_LIGHT_GREEN = (0, 255, 0)
COLOR_LIGHT_YELLOW = (255, 255, 0)
COLOR_BG = (20, 150, 20)

# Road dimensions
ROAD_Y_START = 250
ROAD_WIDTH = 400
LANE_WIDTH = 100
NUM_LANES = 4  # 2 lanes each direction
LANE_MARKING_WIDTH = 3
LANE_MARKING_LENGTH = 30
LANE_MARKING_GAP = 40

# Intersection
INTERSECTION_X = 700
INTERSECTION_WIDTH = 200
CROSSWALK_WIDTH = 80
CROSSWALK_STRIPE_WIDTH = 10

# Vehicle parameters
CAR_NORMAL_LENGTH = 40
CAR_NORMAL_WIDTH = 30
CAR_NORMAL_MAX_SPEED = 120  # pixels/second
CAR_NORMAL_ACCELERATION = 60

TRUCK_LENGTH = 60
TRUCK_WIDTH = 35
TRUCK_MAX_SPEED = 80
TRUCK_ACCELERATION = 40

SPORTS_LENGTH = 45
SPORTS_WIDTH = 32
SPORTS_MAX_SPEED = 150
SPORTS_ACCELERATION = 100

AMBULANCE_LENGTH = 50
AMBULANCE_WIDTH = 33
AMBULANCE_MAX_SPEED = 140
AMBULANCE_ACCELERATION = 90

# Vehicle behavior
SAFE_DISTANCE = 50  # Minimum following distance
EMERGENCY_BRAKE_DISTANCE = 30
LANE_CHANGE_COOLDOWN = 2.0  # seconds
LANE_CHANGE_MIN_GAP = 80
SPAWN_INTERVAL = 2.0  # seconds between spawns
AMBULANCE_SPAWN_CHANCE = 0.05  # 5% chance

# Pedestrian parameters
PEDESTRIAN_SIZE = 15
PEDESTRIAN_SPEED = 40  # pixels/second
PEDESTRIAN_SPAWN_INTERVAL = 5.0  # seconds
CROSSWALK_WAIT_TIME = 1.0  # Wait before crossing

# Traffic light settings
LIGHT_RADIUS = 25
LIGHT_GREEN_TIME = 10.0  # seconds
LIGHT_YELLOW_TIME = 2.0
LIGHT_RED_TIME = 10.0
ADAPTIVE_LIGHT_THRESHOLD = 5  # Queue length to trigger adaptive timing

# Simulation settings
INITIAL_SPAWN_COUNT = 8
TIME_SCALE_MIN = 0.25
TIME_SCALE_MAX = 4.0
TIME_SCALE_STEP = 0.25